# Generated by Django 6.0.1 on 2026-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_chairman', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Board Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CSRInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('livelihood', 'Livelihood')], max_length=50)),
                ('impact_metric', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CSR Initiatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Milestones',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('capacity', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('construction', 'Under Construction'), ('planning', 'Planning'), ('maintenance', 'Maintenance')], max_length=50)),
                ('category', models.CharField(choices=[('coal', 'Coal Power'), ('solar', 'Solar Energy'), ('wind', 'Wind Energy'), ('hydro', 'Hydroelectric'), ('transmission', 'Transmission')], max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('efficiency', models.CharField(blank=True, max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SustainabilityStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('trend', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='🌱', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Sustainability Stats',
                'ordering': ['order'],
            },
        ),
    ]
